name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: change directory
        run: cd Web_app_with_database

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: |
          cd Web_app_with_database
          terraform init

      - name: find security_grp
        run: aws ec2 describe-security-groups --filters "Name=group-name,Values=dove-sg" --query "SecurityGroups[*].GroupId" --output text
      
      - name: import security_grp
        run: terraform import aws_security_group.dove_sg sg-0982c2b36b03c7152 

      - name: Terraform Plan
        run: |
          cd Web_app_with_database
          terraform plan -target=aws_instance.nginx
     
      - name: Terraform Apply
        run: |
          cd Web_app_with_database
          terraform apply -target=aws_instance.nginx -auto-approve
